spring:
  application:
    name: nexign

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc://localhost:5432/nexign
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath:/db/changelog/changelog-main.yml

  messages:
    basename: i18n/messages

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: task_group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"

  data:
    redis:
      host: localhost
      port: 6379

worker:
  count: 5
